from .vertex_ai_comfyui_nodes.imagen import NODE_CLASS_MAPPINGS as IMAGEN_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IMAGEN_DISPLAY_NAME_MAPPINGS
from .vertex_ai_comfyui_nodes.gemini import NODE_CLASS_MAPPINGS as GEMINI_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as GEMINI_DISPLAY_NAME_MAPPINGS
from .vertex_ai_comfyui_nodes.imagen_exp import NODE_CLASS_MAPPINGS as IMAGEN_EXP_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IMAGEN_EXP_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {**IMAGEN_CLASS_MAPPINGS, **GEMINI_CLASS_MAPPINGS, **IMAGEN_EXP_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**IMAGEN_DISPLAY_NAME_MAPPINGS, **GEMINI_DISPLAY_NAME_MAPPINGS, **IMAGEN_EXP_DISPLAY_NAME_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
